name: Costumer Journey - Job

on: 
  schedule: 
    - cron: '*/10 * * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    env:
      working-directory: automation-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm install
        working-directory: '${{ env.working-directory }}'
      - run: npx cypress run --spec **/costumerJourney.cy.js
        working-directory: '${{ env.working-directory }}'
